# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagefield', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('uploadid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.CharField(max_length=10)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Image')),
                ('stationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Station')),
            ],
        ),
    ]
