# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180312_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
